### ISSUE TITLE
memory usage overflow in eval

### ISSUE THREAD

**Issue by Beat-in-our-hearts** [memmelma/VO-Transformer#2]
I successfully trained the VO part of this project, but in the eval process using rl_no_tune.pth, run the cmd command./start_rl.sh --run-type eval --config-yaml configs/rl/evaluation/my_rl.yaml.
The following problem was encountered: the Memory usage increased by 6GB every ten minutes, the GPU memory usage increased by 1GB every ten minutes, and when the server eval reached a certain number of times, the memory usage overflow caused the program to stop.
(In my_rl.yaml, I changed VIDEO_OPTION:[none], other options cause the same problem)

**Comment by memmelma** [comment]
Hey @Beat-in-our-hearts I've also noticed this behavior. My workaround was to run a separate video evaluation on a subset of trajectories (EVAL: TEST_EPISODE_COUNT: 10). Given the video files are quite large, this struck a good balance between wandb storage, video logging, and memory.

I remember debugging the issue and finding that the videos would stay on the GPU. Unfortunately, manually moving them with torch didn't fix it so I stuck with the above.

Lmk if this works for you or if you have more questions!

**Comment by Beat-in-our-hearts** [comment]
我已经收到了哦！感谢来信！！
