### ISSUE TITLE
Why does self.embed(actions) not need to be updated？

### ISSUE THREAD

**Issue by TouchDeeper** [memmelma/VO-Transformer#4]
Hello,

This [line](https://github.com/memmelma/VO-Transformer/blob/48fb458dec1528360ab18b4712ad73ce3e03ee72/pointnav_vo/vo/models/vo_transformer.py#L156) `self.cls_token = torch.nn.Parameter(self.embed(actions).reshape(x.shape[0], 1, EMBED_DIM),requires_grad=False)` set the  grad of `cls_token`  to be none. I think the weight in `self.embed` will not be update in this way.

Why does `self.embed(actions) ` not need to be updated, and how is the initial value set?

**Comment by memmelma** [comment]
Hello @TouchDeeper,

we utilize [torch.nn.Embedding](https://github.com/memmelma/VO-Transformer/blob/48fb458dec1528360ab18b4712ad73ce3e03ee72/pointnav_vo/vo/models/vo_transformer.py#L150) and its corresponding initialization (see pytorch documentation).

You are right, we don't update the action embeddings. However, this is a design decision and we didn't explore setting `requires_grad=True`.

Best,
Marius

**Comment by TouchDeeper** [comment]
@memmelma 
If the cls_token does not update, how can we ensure that the encoding of the cls_token to action is meaningful, as the class_token is just a randomly initialized projection.

**Comment by memmelma** [comment]
@TouchDeeper is a random initialization for each kind of action (forward, turn left, turn right), so the model can learn how to match each of the embeddings to the corresponding action.

**Comment by TouchDeeper** [comment]
@memmelma

I see, but train the cls_token together should also be feasible, right? I've noticed that most of the work is done this way.
